Repository Bavanetha27/Refixly, pull requests merged in 2025-08, with the labels that each got.

#55 added delete account feature
  client/src/components/NavBar.jsx
Labels: beginner, GSSoC'25, Level 1

#60 Improved the UI
  client/package-lock.json
  client/package.json
  client/src/Pages/Community.jsx
  client/src/Pages/Contact.jsx
  client/src/Pages/Home.jsx
  client/src/Pages/LandingPage.jsx
  client/src/Pages/Login.jsx
  client/src/Pages/ProfilePage.jsx
  client/src/Pages/ScanPage.jsx
  client/src/Pages/Signup.jsx
  client/src/Pages/Tutorial.jsx
  client/src/Pages/TutorialsPage.jsx
  client/src/components/FAQAccordion.jsx
  client/src/components/Footer.jsx
  client/src/components/HomeFAQ.jsx
  client/src/components/NavBar.jsx
  client/src/index.css
Labels: gssoc25, level1

#67 [UI Bug] Help Popups Inconsistent with Updated Theme
  client/src/components/Tour.jsx
Labels: gssoc25, level1

#69 Fixed Footer Width & Revamped Design for Consistency (#63)
  client/src/components/Footer.jsx
Labels: gssoc25, level1

#70 Fixed: Repeated Tour Display on Every Page Load (#65)
  client/src/Pages/LandingPage.jsx
Labels: gssoc25, level1

#74 feat: add custom cursor animation for interactive UI elements
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/FluidCursor.jsx
  client/src/hooks/useFluidCursor.js
Labels: gssoc25, level2

#76 feat: Navbar responsiveness on small screens
  client/src/Pages/Home.jsx
  client/src/components/NavBar.jsx
Labels: gssoc25, level1

#77 UI Cleanup — Improved Text Contrast Across the App (#64)
  client/src/Pages/Community.jsx
  client/src/Pages/Contact.jsx
  client/src/Pages/Home.jsx
  client/src/components/HomeFAQ.jsx
Labels: gssoc25, level1

#80 fix(security): restrict access to protected routes for unauthenticated users.
  client/src/App.jsx
  client/src/components/ProtectedRoute.jsx
Labels: gssoc25, level1

#90 pr create automate message added
  .github/workflows/pr-create-automate-message.yml
Labels: gssoc25, level1

#99 fixed the logo problem
  README.md
  client/eslint.config.js
  client/package.json
  client/public/gssoc_logo.png
  client/src/Pages/Tutorial.jsx
  client/src/Pages/TutorialsPage.jsx
  client/src/components/AIDamageDetection.jsx
  client/src/components/FAQAccordion.jsx
  client/src/components/HomeFAQ.jsx
  client/src/context/ThemeContext.jsx
  client/src/context/ThemeProvider.jsx
  client/src/hooks/useFluidCursor.js
Labels: gssoc25, level1

#101 Enhanced Footer Component
  client/src/components/Footer.jsx
Labels: gssoc25, level1
